### PR TITLE
Truncate long string before insert into database

### LINKED ISSUE #264: Can not insert record if the the varlue is very long
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins in container
Controller:
jenkins/jenkins:2.361.4-jdk11
Agent:
jenkins/inbound-agent:4.11.2-4

Postgres:
PostgreSQL 13.6 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit

### Reproduction steps

Run a maven test which causes a very long stack trace.

### Expected Results

No error and the test result is inserted in the database

### Actual Results

```
ERROR: [withMaven] WARNING Exception executing Maven reporter 'Junit Publisher' / org.jenkinsci.plugins.pipeline.maven.publishers.JunitTestsPublisher. Please report a bug associated for the component 'pipeline-maven-plugin' at https://issues.jenkins-ci.org/ 
 hudson.remoting.ProxyException: java.io.IOException: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100000)
```

### Anything else?

I can file a fix but I'd like to know the design.
Shall we increase the varchar size or use text type instead of?
Or truncate the long text to the right size?

### PR DESCRIPTION
**Pull request by topikachu**
Fix #264

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: src/main/java/io/jenkins/plugins/junit/storage/database/DatabaseTestResultStorage.java [hunk 1]
```diff
@@ -39,6 +39,17 @@
...
+    static final int MAX_JOB_LENGTH = 255;
+    static final int MAX_SUITE_LENGTH = 255;
+    static final int MAX_PACKAGE_LENGTH = 255;
+    static final int MAX_CLASSNAME_LENGTH =255;
+    static final int MAX_TEST_NAME_LENGTH =500;
+    static final int MAX_STDOUT_LENGTH =100000;
+    static final int MAX_STDERR_LENGTH =100000;
+    static final int MAX_STACK_TRACE_LENGTH =100000;
+    static final int MAX_ERROR_DETAILS_LENGTH =100000;
+    static final int MAX_SKIPPED_LENGTH =1000;
```
Comment (timja) [inline src/main/java/io/jenkins/plugins/junit/storage/database/DatabaseTestResultStorage.java:51]:
```suggestion
    static final int MAX_JOB_LENGTH = 255;
    static final int MAX_SUITE_LENGTH = 255;
    static final int MAX_PACKAGE_LENGTH = 255;
    static final int MAX_CLASSNAME_LENGTH = 255;
    static final int MAX_TEST_NAME_LENGTH = 500;
    static final int MAX_STDOUT_LENGTH = 100000;
    static final int MAX_STDERR_LENGTH = 100000;
    static final int MAX_STACK_TRACE_LENGTH = 100000;
    static final int MAX_ERROR_DETAILS_LENGTH = 100000;
    static final int MAX_SKIPPED_LENGTH = 1000;
```

**Review by timja — APPROVED** [review]
